# Generated by Django 3.2.19 on 2023-06-05 13:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
