# Generated by Django 3.2.19 on 2023-06-05 20:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='about',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
