# Generated by Django 3.2.19 on 2023-05-30 14:07

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('strip_cover', cloudinary.models.CloudinaryField(max_length=255, verbose_name='cover')),
                ('artist', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100, unique=True)),
                ('year', models.PositiveIntegerField()),
                ('coloring', models.CharField(choices=[('COLOR', 'Color'), ('B&W', 'Black and White'), ('DUOTONE', 'Duotone')], max_length=50)),
                ('binding', models.CharField(choices=[('HC', 'Hardcover'), ('SC', 'Softcover'), ('TP', 'Trade Paperback'), ('FC', 'Floppy'), ('DC', 'Digital')], max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('pages', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
