# Generated by Django 3.2.19 on 2023-05-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripdetail', '0002_alter_stripdetail_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripdetail',
            name='binding',
            field=models.CharField(choices=[('Hardcover', 'Hardcover'), ('Softcover', 'Softcover'), ('Trade Paperback', 'Trade Paperback'), ('Floppy', 'Floppy'), ('Digital', 'Digital')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stripdetail',
            name='coloring',
            field=models.CharField(choices=[('Color', 'Color'), ('Black and White', 'Black and White'), ('Duotone', 'Duotone')], max_length=50),
        ),
    ]
