# Generated by Django 3.2.19 on 2023-06-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripdetail', '0003_auto_20230530_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripdetail',
            options={'ordering': ['title']},
        ),
    ]
